# Generated by Django 5.2.8 on 2025-11-13 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='HobbyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('poem', 'Poem'), ('movie', 'Movie Review'), ('anime', 'Anime Review'), ('blog', 'Blog / Reflection'), ('other', 'Other')], default='blog', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobby_posts', to='profileapp.personalinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
